//
//  PaymentResponse.swift
//  
//
//  Created by ALgy Aly on 15/01/22.
//
//  MIT License
//
//  Copyright (c) 2022 Algy Ali
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

import Foundation

/// Struct that represents the response from the Customer-to-Business (C2B) or Business-to-Customer (B2C) M-Pesa Transactions
/// @responseCode: This gets generated by the iPG platform to indicate the status of the transaction
/// @responseDesc: This gets generated by the iPG platform to indicate the status of the transaction
/// @transactionID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform
/// @conversactionID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform
/// @thirdPartyReference: This is the reference of the third party system. When there are queries about transactions, this will usually be used to track a transaction

public struct PaymentResponse: Decodable {
    public let responseCode       : String
    public let responseDesc       : String
    public let transactionID      : String?
    public let conversactionID    : String?
    public let thirdPartyReference: String
    
    public init(responseCode: String, responseDesc: String, transactionID: String?, conversactionID: String?, thirdPartyReference: String) {
        self.responseCode        = responseCode
        self.responseDesc        = responseDesc
        self.transactionID       = transactionID
        self.conversactionID     = conversactionID
        self.thirdPartyReference = thirdPartyReference
    }
    
    enum CodingKeys: String, CodingKey {
        case responseCode        = "output_ResponseCode"
        case responseDesc        = "output_ResponseDesc"
        case transactionID       = "output_TransactionID"
        case conversactionID     = "output_ConversationID"
        case thirdPartyReference = "output_ThirdPartyReference"
    }
}
